### ISSUE TITLE
ES6 feature: Modules: Tracking Issue

### ISSUE THREAD

**Issue by mikesherov** [jquery/esprima#1000]
## Syntax: 

 * imports:
```
ImportDeclaration :
  import ImportClause FromClause ;
  import ModuleSpecifier ;
ImportClause :
  ImportedDefaultBinding
  NameSpaceImport
  NamedImports
  ImportedDefaultBinding , NameSpaceImport
  ImportedDefaultBinding , NamedImports
ImportedDefaultBinding :
  ImportedBinding
NameSpaceImport :
  * as ImportedBinding
NamedImports :
  { }
  { ImportsList }
  { ImportsList , }
FromClause :
  from ModuleSpecifier
ImportsList :
  ImportSpecifier
  ImportsList , ImportSpecifier
ImportSpecifier :
  ImportedBinding
  IdentifierName as ImportedBinding
ModuleSpecifier :
  StringLiteral
ImportedBinding :
  BindingIdentifier
```
 * exports:
```
ExportDeclaration :
  export * FromClause ;
  export ExportClause FromClause ;
  export ExportClause ;
  export VariableStatement
  export Declaration
  export default HoistableDeclaration[Default]
  export default ClassDeclaration[Default]
  export default [lookahead ∉ {function, class}] AssignmentExpression[In] ;
ExportClause :
  { }
  { ExportsList }
  { ExportsList , }
ExportsList :
  ExportSpecifier
  ExportsList , ExportSpecifier
ExportSpecifier :
  IdentifierName
  IdentifierName as IdentifierName
```

## Spec: 

  * imports: https://people.mozilla.org/~jorendorff/es6-draft.html#sec-imports
  * exports: https://people.mozilla.org/~jorendorff/es6-draft.html#sec-exports

## Remaining Tasks:

 - [x] Land the Classes feature
 - [ ] Review and Test Token Generation
 - [ ] Review Error Messages 
 - [ ] Fix #311 
 - [ ] Address https://github.com/estree/estree/issues/11
 - [ ] Address https://github.com/estree/estree/pulls/38
 - [ ] Address https://github.com/estree/estree/pulls/39
 - [ ] Fix #1077 
 - [ ] Fix #1087 
 - [ ] Fix #1088

**Comment by ikarienator** [comment]
We need to discuss in Wednesday meeting on whether we need to expose an API to parse using different start symbols.

In ES5, the only start symbol is `Script`, so `parse` is unambiguous. In ES6, we have two symbols, `Script` and `Module`. `Module`s are parsed only in strict mode and imports/exports are only allowed in top level of `Module`s.

**Comment by ariya** [comment]
For now, Script vs Module can be handled just like in commit 85fc2f4b from the harmony branch.

**Comment by jeffmo** [comment]
FWIW We've found it useful already (at FB) to add a `nonStrictModule` source type for intermediary conversion-of-codebase purposes. I've been meaning to send this upstream, but wanted to try it downstream first to be sure it's worth it.

(@ariya feel free to say you told me so: https://github.com/jquery/esprima/pull/290#issuecomment-59876225)

Worth considering here too. We found it to be super convenient to be able to opt in to disabling implicit-strict in order to switch existing CJS (etc) modules over to ES6 before having a chance to go through and audit for strict-safety.

**Comment by caridy** [comment]
@jeffmo that's pretty interesting.

**Comment by caridy** [comment]
I plan to work on this this, at least taking the bulk of the work.

**Comment by caridy** [comment]
https://github.com/jquery/esprima/pull/1149
