### ISSUE TITLE
ES6 feature: Classes: tracking Issue

### ISSUE THREAD

**Issue by mikesherov** [jquery/esprima#1001]
## Syntax:

```
ClassDeclaration[Yield, Default] :
  class BindingIdentifier[?Yield] ClassTail[?Yield]
  [+Default] class ClassTail[?Yield]
ClassExpression[Yield,GeneratorParameter] :
  class BindingIdentifier[?Yield]opt ClassTail[?Yield,?GeneratorParameter]
ClassTail[Yield,GeneratorParameter] :
  [~GeneratorParameter] ClassHeritage[?Yield]opt { ClassBody[?Yield]opt }
  [+GeneratorParameter] ClassHeritageopt { ClassBodyopt }
ClassHeritage[Yield] :
  extends LeftHandSideExpression[?Yield]
ClassBody[Yield] :
  ClassElementList[?Yield]
ClassElementList[Yield] :
  ClassElement[?Yield]
  ClassElementList[?Yield] ClassElement[?Yield]
ClassElement[Yield] :
  MethodDefinition[?Yield]
  static MethodDefinition[?Yield]
  ;
 ```

## Spec:

https://people.mozilla.org/~jorendorff/es6-draft.html#sec-class-definitions

## Remaining Tasks:

- [ ] Review and Test Token Generation
- [ ] Review Error Messages 
- [ ] Land Generators Feature
- [ ] @ariya @jeffmo can you fill in more details here?

**Comment by mikesherov** [comment]
@ikarienator is going to tackle this one.

**Comment by RReverser** [comment]
@ikarienator @mikesherov @ariya Please take a look at https://github.com/estree/estree/issues/28 before finalizing this one.
