### ISSUE TITLE
ES6 feature: Default Parameters: tracking Issue

### ISSUE THREAD

**Issue by mikesherov** [jquery/esprima#1005]
## Syntax:

@ariya @jeffmo can you fill this in perhaps?

## Spec:

@ariya @jeffmo can you fill this in perhaps?

## Remaining Tasks:

 - [x] Review and Test Token Generation
 - [x] Review Error Messages
 - [x] review following commits for completeness e1ee12bce3 678988115f ae14b2c069 d3702a251a

**Comment by xjamundx** [comment]
I'm working on adding destructuring and default parameters of this stuff over into `espree` and am running into some trouble when using esprima as a reference.

This simple example that uses the shorthand version of destructuring defaults fails:
```
> esprima.parse("function a({b=10}){}")
Error: Line 1: Unexpected token {
    at createError (/Users/jamuferguson/dev/esprima/esprima.js:2004:21)
    at unexpectedTokenError (/Users/jamuferguson/dev/esprima/esprima.js:2072:13)
    at throwUnexpectedToken (/Users/jamuferguson/dev/esprima/esprima.js:2077:15)
    at parseVariableIdentifier (/Users/jamuferguson/dev/esprima/esprima.js:2981:17)
    at parseParam (/Users/jamuferguson/dev/esprima/esprima.js:3693:17)
    at parseParams (/Users/jamuferguson/dev/esprima/esprima.js:3722:22)
    at parseFunctionDeclaration (/Users/jamuferguson/dev/esprima/esprima.js:3764:15)
    at parseSourceElement (/Users/jamuferguson/dev/esprima/esprima.js:3841:24)
    at parseSourceElements (/Users/jamuferguson/dev/esprima/esprima.js:3877:29)
    at parseProgram (/Users/jamuferguson/dev/esprima/esprima.js:3894:16)
```

This nested destructuring with defaults example also fails in both `master` and `harmony`:
```
> esprima.parse("function a({b=10, a: {x=10}}){}")
Error: Line 1: Unexpected token {
    at createError (/Users/jamuferguson/dev/esprima/esprima.js:2004:21)
    at unexpectedTokenError (/Users/jamuferguson/dev/esprima/esprima.js:2072:13)
    at throwUnexpectedToken (/Users/jamuferguson/dev/esprima/esprima.js:2077:15)
    at parseVariableIdentifier (/Users/jamuferguson/dev/esprima/esprima.js:2981:17)
    at parseParam (/Users/jamuferguson/dev/esprima/esprima.js:3693:17)
    at parseParams (/Users/jamuferguson/dev/esprima/esprima.js:3722:22)
    at parseFunctionDeclaration (/Users/jamuferguson/dev/esprima/esprima.js:3764:15)
    at parseSourceElement (/Users/jamuferguson/dev/esprima/esprima.js:3841:24)
    at parseSourceElements (/Users/jamuferguson/dev/esprima/esprima.js:3877:29)
    at parseProgram (/Users/jamuferguson/dev/esprima/esprima.js:3894:16)
```

There's also some questions regarding what the correct filler is for the `defaults` array when you have less only some defaults applied. While the test shows `[null, "value"]` the actual parser appears to generate `[undefined, "value"]`

For a bit more context: https://github.com/eslint/espree/pull/55

**Comment by ariya** [comment]
@xjamundx I can relate to that: destructuring is a beast and handling correctly it requires several attempts. Unless it is strongly related the issue of default parameter *only*, let's hold off the complication until the default parameter is implemented (which does not mean it is final, depending on how it goes with destructuring).

**Comment by xjamundx** [comment]
Sure, so the only point to add here is to ask for clarity around the filler for the `defaults` array when some  are missing defaults. [This test](https://github.com/jquery/esprima/blob/master/test/test.js#L13023) indicates that it should be `null`, but the actual parser shows:

```
> esprima.parse("function a(a=10, b){}").body[0].defaults
[ { type: 'Literal',
    value: 10,
    raw: '10' },
  undefined ]
```

**Comment by jeffmo** [comment]
cc @DmitrySoshnikov

(who's thought a lot about destructuring stuff while building transpilation support for it over in `jstransform` and `recast`)

**Comment by jeffmo** [comment]
(oops...this issue is more about default params than destructuring...by bad, let's track destructuring stuff in the destructuring issue :p )

**Comment by michaelficarra** [comment]
> destructuring is a beast

I disagree. Destructuring and defaults and rest parameters are not very hard at all. I added these to the Shift parser two weeks ago: https://github.com/shapesecurity/shift-parser-js/pull/45

**Comment by mikesherov** [comment]
This has already been completed.
