### ISSUE TITLE
ES6 feature: Rest Parameters: tracking Issue

### ISSUE THREAD

**Issue by mikesherov** [jquery/esprima#1011]
## Syntax:

```
FormalParameterList[Yield,GeneratorParameter] :
  FunctionRestParameter[?Yield]
  FormalsList[?Yield, ?GeneratorParameter]
  FormalsList[?Yield, ?GeneratorParameter] , FunctionRestParameter[?Yield]
FunctionRestParameter[Yield] :
  BindingRestElement[?Yield]
BindingRestElement[Yield, GeneratorParameter] :
  [+GeneratorParameter] ... BindingIdentifier[Yield]
  [~GeneratorParameter] ... BindingIdentifier[?Yield]
```

## Spec:

https://people.mozilla.org/~jorendorff/es6-draft.html#sec-functions-and-classes

## Remaining Tasks:

 - [x] Review and Test Token Generation
 - [x] Review Error Messages
 - [x] Arrow Function Rest Parameters 
 - [ ] https://github.com/estree/estree/pull/37

**Comment by mikesherov** [comment]
@ariya can you respond to the estree issue about rest and defaults? I think we may want to take acorns approach here.

**Comment by ariya** [comment]
@mikesherov I'm not sure why we want to deviate from the existing SpiderMonkey AST for this case.

**Comment by nzakas** [comment]
Just a heads up: I was doing some experimentation and found that there's no good way to support both the harmony branch `rest` property and the newly-agreed Acorn-like approach (having the rest param in the params array) at the same time. This is because code exists that loops over the params array and then checks to see if `rest` has a value. That means adding the rest param into the params array would result in double evaluation of a rest param.

So we can really only do one or the other but not both (as opposed to `handler` and `handlers`, for instance).

**Comment by mikesherov** [comment]
@nzakas no way to add a flag rather than doing a second loop?

**Comment by nzakas** [comment]
Sure, but that's still a breaking change. My point is that existing code will break if we support both at the same time. If we need a breaking change, might as well go all the way and remove `rest`.

**Comment by mikesherov** [comment]
@nzakas I see, you mean consumer code. I'm +1 for removing all the way.

**Comment by mikesherov** [comment]
@jeffmo ^ ?

**Comment by jeffmo** [comment]
Agreed, let's rip the band-aid off

**Comment by ariya** [comment]
Hmm, maybe I missed something, but when did I discuss keeping the compatibility? Rest parameter was not feature in 2.0 anyway.

**Comment by jeffmo** [comment]
@ariya : I think the breaking-change-ness is only in reference to a breaking change within the harmony branch

**Comment by mikesherov** [comment]
@ariya we sort of glossed over it in the meeting quickly. Glad we're all in agreement to just rip off the baindaid!

**Comment by mikesherov** [comment]
@nzakas, you have sample code for the switch to restElement?

**Comment by nzakas** [comment]
Assuming you mean consumer code that would be confused by having both, escope is a good example: https://github.com/estools/escope/blob/master/src/referencer.js#L221

**Comment by ariya** [comment]
@mikesherov Anything here that is still blocking 2.1?

**Comment by mikesherov** [comment]
@ariya, yes, the switch from defaults/rest properties to resElement/AssigmentPattern
