### ISSUE TITLE
ES6 feature: Arrow Functions: tracking Issue

### ISSUE THREAD

**Issue by mikesherov** [jquery/esprima#1012]
## Syntax:

```
ArrowFunction[In, Yield] :
  ArrowParameters[?Yield] [no LineTerminator here] => ConciseBody[?In]
ArrowParameters[Yield] :
  BindingIdentifier[?Yield]
  CoverParenthesizedExpressionAndArrowParameterList[?Yield]
ConciseBody[In] :
  [lookahead ≠ { ] AssignmentExpression[?In]
  { FunctionBody }
```

## Supplemental Syntax

```
When the production 
  ArrowParameters[Yield] : CoverParenthesizedExpressionAndArrowParameterList[?Yield]
is recognized the following grammar is used to refine the interpretation of
  CoverParenthesizedExpressionAndArrowParameterList :
ArrowFormalParameters[Yield, GeneratorParameter] :
  ( StrictFormalParameters[?Yield, ?GeneratorParameter] )
```

## Spec:

https://people.mozilla.org/~jorendorff/es6-draft.html#sec-arrow-function-definitions

## Remaining Tasks:

 - [x] Review and Test Token Generation
 - [x] Review Error Messages
 - [x] Land Rest Parameters #1011 
 - [x] Fix #1009 
 - [x] Fix #1010 
 - [x] Fix #1013 
 - [x] Fix #1014 
 - [x] Fix #1056
