### ISSUE TITLE
ES6 feature: Destructuring: Tracking Issue

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1045]
# [12.14.5](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-assignment) Destructuring Assignment 

They are used in the left hand side of an assignment expression when `=` is the assignment operator, or at the `LeftHandSideExpression` position of a for-in or a for-of loop. 

Referred to by:
* [12.14.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-assignment-operators-static-semantics-early-errors) Static Semantics: Early Errors
* [13.6.4.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-for-in-and-for-of-statements-static-semantics-early-errors) Static Semantics: Early Errors

## Syntax:

<pre>
<i>AssignmentPattern</i>[Yield] :
  <i>ObjectAssignmentPattern</i><sub>[?Yield]</sub>
  <i>ArrayAssignmentPattern</i><sub>[?Yield]</sub>

<i>ObjectAssignmentPattern</i>[Yield] :
  <b>{</b> <b>}</b>
  <b>{</b> <i>AssignmentPropertyList</i><sub>[?Yield]</sub> <b>}</b>
  <b>{</b> <i>AssignmentPropertyList</i><sub>[?Yield]</sub> <b>,</b> <b>}</b>

<i>ArrayAssignmentPattern</i>[Yield] :
  <b>[</b> <i>Elision</i><sub>opt</sub> <i>AssignmentRestElement</i><sub>[?Yield]</sub><sub>opt</sub> <b>]</b>
  <b>[</b> <i>AssignmentElementList</i><sub>[?Yield]</sub> <b>]</b>
  <b>[</b> <i>AssignmentElementList</i><sub>[?Yield]</sub> , <i>Elision</i><sub>opt</sub> AssignmentRestElement</i><sub>[?Yield]</sub><sub>opt</sub> <b>]</b>

<i>AssignmentPropertyList</i>[Yield] :
  <i>AssignmentProperty</i><sub>[?Yield]</sub>
  <i>AssignmentPropertyList</i><sub>[?Yield]</sub> <b>,</b> <i>AssignmentProperty</i><sub>[?Yield]</sub>

<i>AssignmentElementList</i>[Yield] :
  <i>AssignmentElisionElement</i><sub>[?Yield]</sub>
  <i>AssignmentElementList<sub>[?Yield]</sub> <b>,</b> <i>AssignmentElisionElement</i><sub>[?Yield]</sub>

<i>AssignmentElisionElement</i>[Yield] :
  <i>Elision<sub>opt</sub> <i>AssignmentElement</i><sub>[?Yield]</sub>

<i>AssignmentProperty</i>[Yield] :
  <i>IdentifierReference</i><sub>[?Yield]</sub> <i>Initializer</i><sub>[In,?Yield]</sub><sub>opt</sub>
  <i>PropertyName</i> <b>:</b> <i>AssignmentElement</i><sub>[?Yield]</sub>

<i>AssignmentElement</i>[Yield] :
  <i>DestructuringAssignmentTarget</i><sub>[?Yield]</sub> <i>Initializer</i><sub>[In,?Yield]</sub><sub>opt</sub>

<i>AssignmentRestElement[Yield] :
  <b>...</b> <i>DestructuringAssignmentTarget</i><sub>[?Yield]</sub>

<i>DestructuringAssignmentTarget[Yield] :
  <i>LeftHandSideExpression</i><sub>[?Yield]</sub>
</pre>

## Spec:

Destructuring Assignment: https://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-assignment

Relevant AST interfaces (from https://github.com/estree/estree): (TBD)

## Early Errors:

<pre>
<i>AssignmentProperty</i> : <i>IdentifierReference</i> <i>Initializer</i><sub>opt</sub>
</pre>

* It is a Syntax Error if `IsValidSimpleAssignmentTarget` of `IdentifierReference` is `false`.

<pre>
<i>DestructuringAssignmentTarget</i> : <i>LeftHandSideExpression</i>
</pre>

* It is a Syntax Error if `LeftHandSideExpression` is either an `ObjectLiteral` or an `ArrayLiteral` and if the lexical token sequence matched by `LeftHandSideExpression` cannot be parsed with no tokens left over using `AssignmentPattern` as the goal symbol.

* It is a Syntax Error if `LeftHandSideExpression` is neither an `ObjectLiteral` nor an `ArrayLiteral` and `IsValidSimpleAssignmentTarget(LeftHandSideExpression)` is `false`.

# [13.2.3](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-binding-patterns) Destructuring Binding Patterns

`BindingPattern`s are used in `LexicalBinding`s, `VariableDeclaration`s, `ForBinding`s and `CatchParameter`s. `BindingElement` is also used in `FormalParameter`s. A `BindingElement` is either a `BindingPattern` or a `BindingIdentifier`, optionally followed by a `Initializer`.

## Syntax

<pre>
<i>BindingPattern</i><sub>[Yield,GeneratorParameter]</sub> :
  <i>ObjectBindingPattern</i><sub>[?Yield,?GeneratorParameter]</sub>
  <i>ArrayBindingPattern</i><sub>[?Yield,?GeneratorParameter]</sub>

<i>ObjectBindingPattern</i><sub>[Yield,GeneratorParameter]</sub> :
  <b>{</b> <b>}</b>
  <b>{</b> <i>BindingPropertyList</i><sub>[?Yield,?GeneratorParameter]</sub> <b>}</b>
  <b>{</b> <i>BindingPropertyList</i><sub>[?Yield,?GeneratorParameter]</sub> <b>,</b> <b>}</b>

<i>ArrayBindingPattern</i><sub>[Yield,GeneratorParameter]</sub> :
  <b>[</b> <i>Elision</i><sub>opt</sub> <i>BindingRestElement</i><sub>[?Yield, ?GeneratorParameter]</sub><sub>opt</sub> <b>]</b>
  <b>[</b> <i>BindingElementList</i><sub>[?Yield, ?GeneratorParameter]</sub> <b>]</b>
  <b>[</b> <i>BindingElementList</i><sub>[?Yield, ?GeneratorParameter]</sub> <b>,</b> <i>Elision</i><sub>opt</sub> <i>BindingRestElement</i><sub>[?Yield, ?GeneratorParameter]</sub><sub>opt</sub> <b>]</b>

<i>BindingPropertyList</i><sub>[Yield,GeneratorParameter]</sub> :
  <i>BindingProperty</i><sub>[?Yield, ?GeneratorParameter]</sub>
  <i>BindingPropertyList</i><sub>[?Yield, ?GeneratorParameter]</sub> <b>,</b> <i>BindingProperty</i><sub>[?Yield, ?GeneratorParameter]</sub>

<i>BindingElementList</i><sub>[Yield,GeneratorParameter]</sub> :
  <i>BindingElisionElement</i><sub>[?Yield, ?GeneratorParameter]</sub>
  <i>BindingElementList</i><sub>[?Yield, ?GeneratorParameter]</sub> <b>,</b> <i>BindingElisionElement</i><sub>[?Yield, ?GeneratorParameter]</sub>

<i>BindingElisionElement</i><sub>[Yield,GeneratorParameter]</sub> :
  <i>Elision</i><sub>opt</sub> <i>BindingElement</i><sub>[?Yield, ?GeneratorParameter]</sub>

<i>BindingProperty</i><sub>[Yield,GeneratorParameter]</sub> :
  <i>SingleNameBinding</i><sub>[?Yield, ?GeneratorParameter]</sub>
  <i>PropertyName</i><sub>[?Yield, ?GeneratorParameter]</sub> <b>:</b> <i>BindingElement</i><sub>[?Yield, ?GeneratorParameter]</sub>

<i>BindingElement</i><sub>[Yield,GeneratorParameter]</sub> :
  <i>SingleNameBinding</i><sub>[?Yield, ?GeneratorParameter]</sub>
  [+GeneratorParameter] <i>BindingPattern</i><sub>[?Yield,GeneratorParameter]</sub> <i>Initializer</i><sub>[In]</sub><sub>opt</sub>
  [~GeneratorParameter] <i>BindingPattern</i><sub>[?Yield]</sub> <i>Initializer</i><sub>[In, ?Yield]</sub><sub>opt</sub>

<i>SingleNameBinding</i> <sub>[Yield, GeneratorParameter]</sub> :
  [+GeneratorParameter] <i>BindingIdentifier</i><sub>[Yield]</sub> <i>Initializer</i><sub>[In]</sub><sub>opt</sub>
  [~GeneratorParameter] <i>BindingIdentifier</i><sub>[?Yield]</sub> <i>Initializer</i><sub>[In, ?Yield]</sub><sub>opt</sub>

<i>BindingRestElement</i><sub>[Yield, GeneratorParameter]</sub> :
  [+GeneratorParameter] <b>...</b> <i>BindingIdentifier</i><sub>[Yield]</sub>
  [~GeneratorParameter] <b>...</b> <i>BindingIdentifier</i><sub>[?Yield]</sub>

</pre>

## Spec

Destructuring Binding Patterns: https://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-binding-patterns

Relevant AST interfaces (from https://github.com/estree/estree): (TBD)

#### SpiderMonkey AST

```idl
interface ObjectPattern <: Pattern {
    type: "ObjectPattern";
    properties: [ { key: Literal | Identifier, value: Pattern } ];
}

interface ArrayPattern <: Pattern {
    type: "ArrayPattern";
    elements: [ Pattern | null ];
}
```

#### Shift AST

```webidl
typedef (ObjectBinding or ArrayBinding or BindingIdentifier or MemberExpression) Binding;


interface BindingWithDefault : Node {
  attribute (ObjectBinding or ArrayBinding or BindingIdentifier) binding;
  attribute Expression init;
};

interface BindingIdentifier : Node {
  attribute Identifier identifier;
};

interface ArrayBinding : Node {
  attribute (Binding or BindingWithDefault)?[] elements;
  attribute BindingIdentifier? restElement;
};

interface ObjectBinding : Node {
  attribute BindingProperty[] properties;
};

interface BindingProperty : Node { };

interface BindingPropertyIdentifier : BindingProperty {
  attribute BindingIdentifier identifier;
  attribute Expression? init;
};

interface BindingPropertyProperty : BindingProperty {
  attribute PropertyName name;
  attribute (Binding or BindingWithDefault) binding;
};


interface PropertyName : Node { };

interface ComputedPropertyName : PropertyName {
  attribute Expression value;
};

interface StaticPropertyName : PropertyName {
  attribute string value;
};

```

## Related Tasks:

- [ ] Destructuring default #1028 (previous [issue 565](https://code.google.com/p/esprima/issues/detail?id=565))
- [ ] Previous [issue 489](https://code.google.com/p/esprima/issues/detail?id=489)
- [x] [Step 1](https://github.com/jquery/esprima/issues/1118)
