### ISSUE TITLE
Modularization and code reorganization

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1440]
This is a meta issue to summarize and capture the modularization activities towards version 3.0:

#### Modularization

- [x] #1177 Migrate to ES6/TypeScript
- [x] #1176 Split the parser vs the rest
- [x] #1390 Refactor error handling code out of the parser
- [x] #1389 Refactor the pure tokenizer to its own file
- [x] #1397 Refactor the reader algorithm
- [x] #1374 Split the state tracking between parsing vs scanning
- [x] #1404 Reduce duplicated code to handle directives
- [x] #1427 Move the exported entry points to the main source
- [x] #1422 Separate API tests

#### Code reorganization and improvements

- [x] #1111 Parse regular expression outside the scanner
- [x] #1368 Track strict mode in the parser vs the scanner
- [x] #1381 Collect comments without callback handler
- [x] #1401 Formalize the constructors for the AST nodes
- [x] #1414 Consistent construction of a method definition node
- [x] #1418 Eliminate the post-processing step of token location filtering
- [x] #1434 Reimplement comment handling with the parser delegate
- [x] #1410 Major parser overhaul

**Comment by ariya** [comment]
The refactoring activity is declared as *completed*.
