### ISSUE TITLE
Release 3.1

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1584]
Time to refresh the 3.x series!

- [x] Bump version number
- [x] Update ChangeLog
- [x] Update devDependencies
- [x] Check for performance regression
- [x] Tag the repository
- [x] Publish to npm
- [x] Update web site

What goes into this release? Just some backported updates from the master branch.

**Comment by ariya** [comment]
The npm package has been published and the web site has been updated. Enjoy the release!
