### ISSUE TITLE
Release 4.0

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1589]
- [x] Bump version number
- [x] Update ChangeLog
- [x] Update devDependencies
- [x] Check for performance regression
- [x] Tag the repository
- [x] Publish to npm
- [x] Build the doc on readthedocs
- [x] Announce in the mailing-list
- [x] Update web site

What goes into this release? New ES2017 syntax support:
- [x] #1550 Trailing commas in function parameter lists and calls 
- [x] #1079 Async Function and await expression 

API change:
- [x] #1577 Emphasize `parseScript` vs `parseModule`

Other relevant improvements:
- [x] #1477 Host extensive documentation at https://esprima.readthedocs.io
- [x] #1572 Use TypeScript 2.0
- [x] #1720 Refactoring and clean-up
- [x] #1727 Run browser tests with Microsoft Edge
- [x] #1836 Run CI with Node.js v8

And tons of various fixes!
- [x] #1786 Fix JSX non-empty container
- [x] #1765 Allow JSX element in a yield expression
- [x] #1793 Allow `in` expression in a concise body with a function body
- [x] #1693 Setter function argument must not be a rest parameter
- [x] #1677 Limit strict mode directive to functions with a simple parameter list
- [x] #1612 Prohibit any escape sequence in a reserved word
- [x] #1619 Only permit hex digits in hex escape sequence
- [x] #1484 Prohibit labelled class/generator/function declaration
- [x] #1657 Limit function declaration as if statement clause only in non-strict mode
- [x] #1481 Tolerate missing ) in a with and do-while statement

**Comment by ariya** [comment]
Looks like we need to keep only _trailing commas_ and _async/await_ for 4.0.

From the most recent TC-39 meeting on [Jan 24-26](https://github.com/tc39/agendas/blob/master/2017/01.md), the above two are the only syntax changes which made it to the [expected 2017 spec](https://github.com/tc39/proposals/blob/master/finished-proposals.md).

Any other opinions and perspectives (perhaps from the Foundation representatives on TC-39) will be appreciated.

**Comment by hzoo** [comment]
Yeah the other 2 are stage-3 are still I believe

**Comment by ariya** [comment]
Also useful: http://www.2ality.com/2016/02/ecmascript-2017.html.

**Comment by ariya** [comment]
Non-ES2017 syntax features are bumped to major version update 5.0 (#1743).

**Comment by samgurtman** [comment]
Question: What is the release time line for this, for those of us already using ES2017 feature?

**Comment by ariya** [comment]
@samgurtman Keep an eye on the projects page: https://github.com/jquery/esprima/projects.

**Comment by samgurtman** [comment]
Thanks!

**Comment by joseandrespg** [comment]
Hi! 

Do we have an estimate release date for this version? The previous one was due in April. 

We would love to use this new ES2017 support! Thanks!

**Comment by ariya** [comment]
No noticeable performance difference is observed.

Version 3.1.3:
```
    Underscore 1.5.2    42.5 KiB      4.94 ms ± 0.88%
      Backbone 1.1.0    58.7 KiB      5.08 ms ± 3.34%
      MooTools 1.4.5   156.7 KiB     23.05 ms ± 0.59%
        jQuery 1.9.1   262.1 KiB     25.30 ms ± 1.06%
          YUI 3.12.0   330.4 KiB     23.31 ms ± 0.41%
 jQuery.Mobile 1.4.2   442.2 KiB    102.11 ms ± 5.33%
       Angular 1.2.5   701.7 KiB     71.23 ms ± 5.10%
                     ------------------------
                      1994.3 KiB    255.02 ms ± 4.36%
```

Version 4.0.0:
```
    Underscore 1.5.2    42.5 KiB      4.85 ms ± 0.71%
      Backbone 1.1.0    58.7 KiB      4.72 ms ± 0.64%
      MooTools 1.4.5   156.7 KiB     22.43 ms ± 0.49%
        jQuery 1.9.1   262.1 KiB     32.00 ms ± 7.82%
          YUI 3.12.0   330.4 KiB     23.32 ms ± 0.40%
 jQuery.Mobile 1.4.2   442.2 KiB     93.42 ms ± 4.32%
       Angular 1.2.5   701.7 KiB     73.53 ms ± 4.37%
                     ------------------------
                      1994.3 KiB    254.26 ms ± 4.49%
```
(Tested with Node.js 8.0, using V8 5.8)

**Comment by ariya** [comment]
The npm package has been published and the web site has been updated. Enjoy the release!
