### ISSUE TITLE
Refactoring and clean-up

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1720]
This is a meta issue tracking all relevant refactoring for 4.0:

- [x] #1702 Eliminate token object mutation
- [x] #1714 Remove unnecessary token mutation when creating a primary
- [x] #1703 Use the new type assertion syntax
- [x] #1705 Type annotations on all tokenization-related code
- [x] #1711 Check for EOF with the lookahead token
- [x] #1712 Let the Token enum be a const
- [x] #1768 Simplify token choice in the Tokenizer class
- [x] #1713 Use member access modifier in the scanner
- [x] #1716 Save and restore scanner state
- [x] #1717 Merge the different structures to manage node location

**Comment by ariya** [comment]
Each planned refactoring task has been completed.
