### ISSUE TITLE
ES6 feature: Modules: Tracking Issue

### ISSUE THREAD

**Issue by mikesherov** [jquery/esprima#313]
In order to land modules, we must:

 - [ ] Land the Classes feature
 - [ ] Review and Test Token Generation
 - [ ] Review Error Messages 
 - [ ] Fix #311 

The espree fork may land it shortly as well, so we have the benefit of those dependencies as well https://github.com/eslint/espree/pull/43

**Comment by mikesherov** [comment]
@ariya can you confirm that this is the known set of tasks for modules? cc @caridy

**Comment by caridy** [comment]
LGTM

**Comment by ariya** [comment]
We need to provide a structure/template for feature inclusion. A possible example is https://code.google.com/p/esprima/issues/detail?id=621.

**Comment by mikesherov** [comment]
@ariya fair enough. I'll submit a PR for a template. In this case, feel like modifying the description to also include the BNF description of Module Syntax?

**Comment by mikesherov** [comment]
@ariya: https://github.com/jquery/esprima/pull/315

**Comment by mikesherov** [comment]
@ariya added maintainers guide with section on proposing features for inclusion: https://github.com/jquery/esprima/wiki/maintainers-guide Let me know if that looks right, and if so, I'll fix up this description and the one for classes.

**Comment by mikesherov** [comment]
Closed in favor of #1000
