### ISSUE TITLE
ES6 feature: Classes: tracking issue

### ISSUE THREAD

**Issue by mikesherov** [jquery/esprima#314]
In order to land classes, we must:
 
- [ ] Review and Test Token Generation
- [ ] Review Error Messages 
- [ ] @ariya @jeffmo can you fill in more details here?

**Comment by mikesherov** [comment]
Closing in favor of #1001
